### ISSUE TITLE
integrating nodejs support

### ISSUE THREAD

**Issue by mreinstein** [shubhamjain/whistlerr#1]
@shubhamjain thanks for exposing this, cool demo!

I'd love to use this from the command line, by piping data from alsa/sox into this. 

How hard would it be to pipe the microphone data from something like https://github.com/vincentsaluzzo/node-microphone  into this logic?

**Comment by mreinstein** [comment]
actually this might be better, as it supposedly works with both node and browsers: 

https://www.npmjs.com/package/audio-render

It looks like this module provides a `getByteTimeDomainData(time_buf)` method which seems to be the primary way your detection code slurps data out of the microphone stream.

Assuming this is something you're open to, happy to send a pull request

**Comment by mreinstein** [comment]
@shubhamjain I've got this working in node! I set up a temporary repository here:

https://github.com/mreinstein/node-whistlerr

What I'd like to do is merge my logic into your repo, and publish this as a package on npm so that it will be more useful to developers, regardless of what environment (node or browser) that they're using.

Is this something you'd be interested in? Happy to help!

**Comment by shubhamjain** [comment]
Thanks for the effort, Mike. I would definitely be interested in packaging this as node module. But would it more useful as a standalone node package, working with something like node-web-audio-api or as a browser library?

I need to re-visit the code I wrote two years back and see if it could be generalised more on things it does.

**Comment by mreinstein** [comment]
> would it more useful as a standalone node package, working with 
> something like node-web-audio-api or as a browser library?

Ideally it could be used across node or the browser.  I'm happy to do the plumbing on setting up a build step so this would produce a standalone browser build, + one that works for browserify/nodejs.


> I need to re-visit the code I wrote two years back and see
> if it could be generalised more on things it does.

The biggest issue right now is configurability. The logic is hardcoded to use a 44k sample rate as described in #2. this works great in mac os x, windows, etc. but on my raspberry pi (which has a lot less power) it chokes and can't keep up, pegging the cpu near 100% utilization. enabling this to run at 16k sample rate would help a lot. Also any documentation on tweakable/tunable parameters would be fantastic. I'm still messing around with trying to figure out how to decrease false positives (identifying things that aren't really whistles as whistles) and this information/docs would be super helpful.

**Comment by shubhamjain** [comment]
I have started revisiting the code to make it better. I has thousands of things wrong — single-letter variable names, not enough comments, archaic coding style. Even the research paper it's based on is paywalled. Hopefully, would be able to make it better and generalise it in few weeks.

**Comment by mreinstein** [comment]
sounds good! If there's any way I can help happy to donate a little time.

Right now I don't have enough information to accurately use this module. I need to understand how to tune things to reduce false positives. #2 would also be helpful because i'm trying to run this on raspberry pi, and 44khz sample rate seems to slow things down quite a bit.

**Comment by shubhamjain** [comment]
So I have made few changes. 

First, I have modularised the code to use webpack and different files. It helped me understand my code better (and not to deny the positive vibes of well-organised code).

Second, I have fixed a major performance issue, where I was duplicating arrays using a combination of `JSON.stringify` and  `JSON.parse`. As it was happening quite frequently, it added a major load to the CPU. 

I still need to understand DSP more to better implement the filters and variable sample rates. Let me know if this helped with your performance problems.

**Comment by mreinstein** [comment]
looks like good progress!

**Comment by shubhamjain** [comment]
@mreinstein Is it possible for you to deregister whistlerr, so that I can push this code on NPM? That'd make it easier to push updates and avoid confusion.

**Comment by mreinstein** [comment]
@shubhamjain 

>  Is it possible for you to deregister whistlerr, so that I can push this code on NPM? 

Definitely. Would you be open to some cleanup pull requests before we publish? I'm happy to send some improvements.

**Comment by mreinstein** [comment]
@shubhamjain #3 I just sent. Can you take a look and see what you think of these changes?

From a high level, here's what I added:

* `whistlerr` works in both node and browser
* changed the API to accept a config object
* support the ability to have more than 1 whistlerr instance in a program
* added demo for node
* added some polyfills for `requestAnimationFrame` and `getUserMedia` (they have different prefixes in different browsers)

I've tested these changes in both the browser and node, they seem to work.

Would love some feedback on this. :)

**Comment by shubhamjain** [comment]
#3 has been merged.
