### ISSUE TITLE
how can I use this with 16000 sample rate?

### ISSUE THREAD

**Issue by mreinstein** [shubhamjain/whistlerr#2]
@shubhamjain  I noticed that the code assumes `44100` sample rate, but my audio is being collected @ `16000`.

I tried modifying a few variables in the code, but this didn't seem to work. I must have missed a few.

Any help would be greatly appreciated. :)

**Comment by shubhamjain** [comment]
I tried whistlerr with 16KHz sample rate and although, I couldn't reach a general solution that would work for all the rates, I did find that you can modify the existing parameters to make it work for particular one. 

Basically, whistlerr works on three features. First, Jensen Difference, Whistle Block Ratio and Positive Samples / 50 Samples. Using the newer code, you can modify them using .setConfig() (Please check whistle.js). In my case, I was able to reach approximation by tweaking jDiffThreshold from `0.45` to `0.25` and changing the sample rate. 

Unfortunately, there is no good way to simulate 16Khz of microphone input. I only got close by using  few audio files with custom sample rates. 

Let me know if that works for you.

**Comment by mreinstein** [comment]
hi @shubhamjain !

> I couldn't reach a general solution that would work for all the rates

I think even just supporting 16khz and 44khz would be a great improvement, since those seem to be 2 very common sample rates for wav files.  Perhaps it could be a config variable that is passed in, and the code would error out if the sample rate doesn't match one of the predefined allowed values.

> Unfortunately, there is no good way to simulate 16Khz of microphone input

When I produced the nodejs port of your code, I used a microphone module that supports setting the microphone sample rate:

https://github.com/mreinstein/node-whistlerr

take a look in `examples/node/index.js`. You'll see `SAMPLE_RATE` variable which is currently set to 44100. You can change this line and modify it to 16000, and run `node examples/node/index.js` to get 16khz sampled mic data flowing into whistler

**Comment by mreinstein** [comment]
I've deleted my `node-whistlerr` repo in favor of your module. You can now see the same example of node mic usage in https://github.com/shubhamjain/whistlerr/blob/master/demo/node/index.js#L40
